import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { stringify } from "yaml";
import type { ModelDefinition } from "@aiandrelay/models";
import { getCodexSupportedModels, type CodexModelSelection } from "../codex/defaults.js";
import { AIAND_BASE_URL } from "../aiand-core.js";
import { aiandrelayHome } from "../paths.js";

/**
 * DeepSeek Harness (`dsh`) support.
 *
 * `dsh` is configured through "cordis" patch files: a YAML document that
 * declares plugins/providers and is layered over its built-in config. We write
 * a patch that adds ai& as a custom `openai-completions` provider and pins
 * the default model, then point `dsh` at that file for the launch. Nothing in
 * the file is a credential - the API key is passed by env var - so it is safe
 * to keep on disk and reuse.
 */

export const DEEPSEEK_PROVIDER_ID = "aiandrelay";
export const DEEPSEEK_API_KEY_ENV = "AIAND_API_KEY";
export const NATIVE_DEEPSEEK_API_KEY_ENV = "DEEPSEEK_API_KEY";

type DeepseekModel = {
  id: string;
  name: string;
  contextWindow: number;
  maxTokens: number;
  input: Array<"text" | "image">;
};

export type DeepseekPatch = Array<Record<string, unknown>>;

export type DeepseekLaunchSpec = {
  binary: "dsh";
  args: string[];
  env: NodeJS.ProcessEnv;
};

function modelInput(model: ModelDefinition): Array<"text" | "image"> {
  return model.attachment && model.modalities.input.includes("image")
    ? ["text", "image"]
    : ["text"];
}

export function buildDeepseekPatch(
  selectedModel: CodexModelSelection,
  baseUrl = AIAND_BASE_URL,
  nativeDeepseekApiKey = process.env[NATIVE_DEEPSEEK_API_KEY_ENV],
): DeepseekPatch {
  const models: DeepseekModel[] = getCodexSupportedModels().map(({ definition }) => ({
    id: definition.id,
    name: definition.name,
    contextWindow: definition.limit.context,
    maxTokens: definition.limit.output,
    input: modelInput(definition),
  }));

  const patch: DeepseekPatch = [
    {
      id: "llm-pi-ai",
      config: {
        providers: {
          [DEEPSEEK_PROVIDER_ID]: {
            displayName: "ai& via ai& Relay",
            apiKeyEnv: DEEPSEEK_API_KEY_ENV,
            api: "openai-completions",
            baseURL: baseUrl,
            // ai& runs an OpenAI-compatible stack that does not implement the
            // OpenAI "developer" role; keep the system prompt as a system message.
            compat: { supportsDeveloperRole: false, supportsReasoningEffort: true },
            models,
          },
        },
      },
    },
    {
      id: "agent-default-model",
      config: { provider: DEEPSEEK_PROVIDER_ID, model: selectedModel.id },
    },
  ];

  // Only disable the built-in DeepSeek provider when the user has no native
  // DeepSeek key - otherwise leave their own provider available alongside ours.
  if (!nativeDeepseekApiKey?.trim()) {
    patch.push({ id: "llm-deepseek", disabled: true });
  }
  return patch;
}

export function buildDeepseekPatchSource(
  selectedModel: CodexModelSelection,
  baseUrl = AIAND_BASE_URL,
  nativeDeepseekApiKey = process.env[NATIVE_DEEPSEEK_API_KEY_ENV],
): string {
  return `# Generated by ai& Relay. Model metadata only; no credentials.\n${stringify(
    buildDeepseekPatch(selectedModel, baseUrl, nativeDeepseekApiKey),
  )}`;
}

/**
 * Content-addressed patch path: the filename embeds a hash of the patch body,
 * so a changed model catalog writes a new file instead of silently reusing a
 * stale one, and repeat launches with identical config reuse the same file.
 */
export function resolveDeepseekPatchPath(
  selectedModel: CodexModelSelection,
  baseUrl = AIAND_BASE_URL,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const contentHash = createHash("sha256")
    .update(buildDeepseekPatchSource(selectedModel, baseUrl, env[NATIVE_DEEPSEEK_API_KEY_ENV]))
    .digest("hex")
    .slice(0, 12);
  return join(aiandrelayHome(), "deepseek-harness", `aiand-provider-${contentHash}.cordis.yml`);
}

export async function writeDeepseekPatch(
  filePath: string,
  selectedModel: CodexModelSelection,
  baseUrl = AIAND_BASE_URL,
  nativeDeepseekApiKey = process.env[NATIVE_DEEPSEEK_API_KEY_ENV],
): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(
    filePath,
    buildDeepseekPatchSource(selectedModel, baseUrl, nativeDeepseekApiKey),
    { encoding: "utf8", mode: 0o600 },
  );
}

function argsWithoutPatchOverrides(args: string[]): string[] {
  const sanitized: string[] = [];
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--patch") {
      index += 1;
      continue;
    }
    if (arg?.startsWith("--patch=")) {
      continue;
    }
    if (arg !== undefined) {
      sanitized.push(arg);
    }
  }
  return sanitized;
}

export function buildDeepseekLaunchSpec({
  apiKey,
  baseUrl,
  patchPath,
  passthrough,
  env = process.env,
}: {
  apiKey: string;
  baseUrl: string;
  patchPath: string;
  passthrough: string[];
  env?: NodeJS.ProcessEnv;
}): DeepseekLaunchSpec {
  return {
    binary: "dsh",
    // `dsh web` launches its local web UI; --patch layers our provider config
    // over its defaults. A user-supplied --patch is stripped so ours applies.
    args: ["web", "--patch", patchPath, ...argsWithoutPatchOverrides(passthrough)],
    env: {
      ...env,
      [DEEPSEEK_API_KEY_ENV]: apiKey,
      AIAND_BASE_URL: baseUrl,
    },
  };
}
