/**
 * Offline snapshot of the ai& OpenAI model catalog (`GET /v1/models`),
 * captured 2026-08-16. Used as the fallback when the live fetch fails or has
 * not run yet, and as the deterministic source for named model constants the
 * test-suite imports.
 *
 * Regenerate with: `pnpm --filter @aiandrelay/models regen-catalog`
 * (requires `AIAND_API_KEY`). Only the fields `buildCatalog()` reads are kept.
 */
import type { AiandApiModel } from "./index.js";

export const CATALOG_SNAPSHOT: readonly AiandApiModel[] = [
  {
    id: "zai-org/glm-5.2",
    name: "zai-org/glm-5.2",
    owned_by: "ai&",
    provider: "zai-org",
    context_window: 1_048_576,
    capabilities: ["reasoning", "tool_calling"],
    reasoning_efforts: ["none", "high", "max"],
    reasoning_effort_default: "max",
    currency: "jpy",
    input_per_1m: "160.000000",
    output_per_1m: "650.000000",
    cached_input_per_1m: "40.000000",
  },
  {
    id: "moonshotai/kimi-k2.7-code",
    name: "moonshotai/kimi-k2.7-code",
    owned_by: "ai&",
    provider: "moonshotai",
    context_window: 262_144,
    capabilities: ["reasoning", "tool_calling", "vision", "document"],
    reasoning_efforts: ["high"],
    reasoning_effort_default: "high",
    description: "Kimi K2.7-Code by Moonshot AI",
    currency: "jpy",
    input_per_1m: "125.000000",
    output_per_1m: "560.000000",
    cached_input_per_1m: "30.000000",
  },
  {
    id: "moonshotai/kimi-k3",
    name: "moonshotai/kimi-k3",
    owned_by: "ai&",
    provider: "moonshotai",
    context_window: 1_048_576,
    capabilities: ["reasoning", "tool_calling", "vision", "document"],
    reasoning_efforts: ["low", "high", "max"],
    reasoning_effort_default: "max",
    currency: "jpy",
    input_per_1m: "480.000000",
    output_per_1m: "2000.000000",
    cached_input_per_1m: "80.000000",
  },
  {
    id: "deepseek-ai/deepseek-v4-pro",
    name: "deepseek-ai/DeepSeek-V4-Pro",
    owned_by: "ai&",
    provider: "deepseek-ai",
    context_window: 1_048_576,
    capabilities: ["reasoning", "tool_calling"],
    reasoning_efforts: ["none", "high", "max"],
    reasoning_effort_default: "none",
    description: "DeepSeek-V4-Pro",
    currency: "jpy",
    input_per_1m: "160.000000",
    output_per_1m: "400.000000",
    cached_input_per_1m: "30.000000",
  },
  {
    id: "motif-technologies/motif-3",
    name: "Motif-Technologies/Motif-3",
    owned_by: "ai&",
    provider: "Motif-Technologies",
    context_window: 262_144,
    capabilities: ["chat", "reasoning"],
    reasoning_efforts: ["low", "medium", "high"],
    reasoning_effort_default: "medium",
    description:
      "Motif 3 is a large-scale, decoder-only Mixture-of-Experts (MoE) language model with 314 billion total parameters and 13.2 billion parameters activated per token.",
    currency: "jpy",
    input_per_1m: "80.000000",
    output_per_1m: "320.000000",
    cached_input_per_1m: "30.000000",
  },
  {
    id: "deepseek-ai/deepseek-v4-flash",
    name: "deepseek-ai/DeepSeek-V4-Flash",
    owned_by: "ai&",
    provider: "deepseek-ai",
    context_window: 1_048_576,
    capabilities: ["reasoning", "tool_calling"],
    reasoning_efforts: ["none", "high", "max"],
    reasoning_effort_default: "none",
    description: "DeepSeek-V4-Flash",
    currency: "jpy",
    input_per_1m: "25.000000",
    output_per_1m: "40.000000",
    cached_input_per_1m: "10.000000",
  },
  {
    id: "qwen/qwen3.6-27b",
    name: "qwen/qwen3.6-27b",
    owned_by: "ai&",
    provider: "qwen",
    context_window: 262_144,
    capabilities: ["reasoning", "tool_calling", "vision", "video", "document"],
    reasoning_efforts: ["none", "high"],
    reasoning_effort_default: "high",
    description: "Qwen3.6-27B",
    currency: "jpy",
    input_per_1m: "50.000000",
    output_per_1m: "510.000000",
    cached_input_per_1m: "30.000000",
  },
  {
    id: "google/gemma-4-31b-it",
    name: "google/gemma-4-31b-it",
    owned_by: "ai&",
    provider: "google",
    context_window: 262_144,
    capabilities: ["reasoning", "tool_calling", "vision", "video", "document"],
    reasoning_efforts: ["none", "high"],
    reasoning_effort_default: "none",
    description: "Google Gemma 4 31B instruction-tuned",
    currency: "jpy",
    input_per_1m: "30.000000",
    output_per_1m: "80.000000",
    cached_input_per_1m: "8.000000",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "openai/gpt-oss-120b",
    owned_by: "ai&",
    provider: "openai",
    context_window: 131_072,
    capabilities: ["reasoning", "tool_calling"],
    reasoning_efforts: ["low", "medium", "high"],
    reasoning_effort_default: "medium",
    currency: "jpy",
    input_per_1m: "25.000000",
    output_per_1m: "95.000000",
    cached_input_per_1m: "10.000000",
  },
];
